// Generated by GitHub Copilot
import * as pc from 'playcanvas';
import { useEffect, useRef } from 'react';

const CAMERA_NEAR = 0.1;
const CAMERA_FAR = 2000;

/**
 * Computes a combined AABB from all mesh instances under the provided entity.
 * @param {pc.Entity} rootEntity
 * @returns {pc.BoundingBox | null}
 */
function computeCombinedAabb(rootEntity) {
  const renders = rootEntity.findComponents('render');

  if (!renders.length) {
    return null;
  }

  let merged = null;

  for (const renderComponent of renders) {
    for (const meshInstance of renderComponent.meshInstances) {
      if (merged) {
        merged.add(meshInstance.aabb);
      } else {
        merged = meshInstance.aabb.clone();
      }
    }
  }

  return merged;
}

/**
 * Calculates camera position from yaw/pitch/distance orbit values.
 * @param {number} yaw
 * @param {number} pitch
 * @param {number} distance
 * @param {pc.Vec3} target
 * @returns {pc.Vec3}
 */
function getOrbitPosition(yaw, pitch, distance, target) {
  const yawRad = yaw * pc.math.DEG_TO_RAD;
  const pitchRad = pitch * pc.math.DEG_TO_RAD;
  const x = target.x + distance * Math.cos(pitchRad) * Math.sin(yawRad);
  const y = target.y + distance * Math.sin(pitchRad);
  const z = target.z + distance * Math.cos(pitchRad) * Math.cos(yawRad);

  return new pc.Vec3(x, y, z);
}

/**
 * Renders a PlayCanvas viewport and loads a GLB model from a URL.
 * @param {{
 *   modelUrl: string,
 *   modelName: string,
 *   onStatusChange: (status: string) => void
 * }} props
 * @returns {JSX.Element}
 */
export default function ModelViewer({ modelUrl, modelName, onStatusChange }) {
  const canvasRef = useRef(null);

  useEffect(() => {
    if (!canvasRef.current) {
      return undefined;
    }

    const canvas = canvasRef.current;

    const app = new pc.Application(canvas, {
      mouse: new pc.Mouse(canvas),
      touch: new pc.TouchDevice(canvas),
      keyboard: new pc.Keyboard(globalThis),
      graphicsDeviceOptions: {
        antialias: true,
        alpha: false,
        powerPreference: 'high-performance'
      }
    });

    app.start();
    app.graphicsDevice.maxPixelRatio = Math.min(globalThis.devicePixelRatio || 1, 2);
    app.setCanvasFillMode(pc.FILLMODE_NONE);
    app.setCanvasResolution(pc.RESOLUTION_AUTO);
    app.scene.gammaCorrection = pc.GAMMA_SRGB;
    app.scene.toneMapping = pc.TONEMAP_ACES;
    app.scene.skyboxIntensity = 1;
    app.scene.ambientLight = new pc.Color(0.32, 0.34, 0.38);

    const resizeCanvas = () => {
      app.resizeCanvas(canvas.clientWidth, canvas.clientHeight);
    };

    resizeCanvas();
    globalThis.addEventListener('resize', resizeCanvas);

    const camera = new pc.Entity('camera');
    camera.addComponent('camera', {
      clearColor: new pc.Color(0.94, 0.95, 0.93),
      nearClip: CAMERA_NEAR,
      farClip: CAMERA_FAR
    });
    app.root.addChild(camera);

    const keyLight = new pc.Entity('keyLight');
    keyLight.addComponent('light', {
      type: 'directional',
      color: new pc.Color(1, 0.95, 0.9),
      castShadows: true,
      intensity: 2.4,
      shadowBias: 0.2,
      normalOffsetBias: 0.05,
      shadowResolution: 2048,
      shadowDistance: 80
    });
    keyLight.setEulerAngles(45, 30, 0);
    app.root.addChild(keyLight);

    const fillLight = new pc.Entity('fillLight');
    fillLight.addComponent('light', {
      type: 'directional',
      color: new pc.Color(0.73, 0.82, 1),
      intensity: 0.75
    });
    fillLight.setEulerAngles(25, -130, 0);
    app.root.addChild(fillLight);

    const rimLight = new pc.Entity('rimLight');
    rimLight.addComponent('light', {
      type: 'directional',
      color: new pc.Color(1, 0.92, 0.82),
      intensity: 0.45
    });
    rimLight.setEulerAngles(-15, 160, 0);
    app.root.addChild(rimLight);

    const orbit = {
      yaw: 45,
      pitch: -18,
      distance: 12,
      target: new pc.Vec3(0, 0, 0)
    };

    let isDragging = false;
    let dragLastX = 0;
    let dragLastY = 0;
    let modelEntity = null;

    /**
     * Updates camera transform based on orbit values.
     * @returns {void}
     */
    function applyOrbitCamera() {
      const cameraPosition = getOrbitPosition(orbit.yaw, orbit.pitch, orbit.distance, orbit.target);
      camera.setPosition(cameraPosition);
      camera.lookAt(orbit.target);
    }

    /**
     * Handles pointer down to start orbit drag.
     * @param {MouseEvent} event
     * @returns {void}
     */
    function handlePointerDown(event) {
      if (event.button !== 0) {
        return;
      }

      isDragging = true;
      dragLastX = event.clientX;
      dragLastY = event.clientY;
    }

    /**
     * Handles pointer move for camera orbit rotation.
     * @param {MouseEvent} event
     * @returns {void}
     */
    function handlePointerMove(event) {
      if (!isDragging) {
        return;
      }

      const deltaX = event.clientX - dragLastX;
      const deltaY = event.clientY - dragLastY;
      dragLastX = event.clientX;
      dragLastY = event.clientY;

      orbit.yaw -= deltaX * 0.25;
      orbit.pitch = pc.math.clamp(orbit.pitch - deltaY * 0.2, -85, 30);
    }

    /**
     * Stops orbit drag when pointer is released.
     * @returns {void}
     */
    function handlePointerUp() {
      isDragging = false;
    }

    /**
     * Handles wheel for camera zoom.
     * @param {WheelEvent} event
     * @returns {void}
     */
    function handleWheel(event) {
      event.preventDefault();
      orbit.distance = pc.math.clamp(orbit.distance + event.deltaY * 0.01, 1.5, 300);
    }

    canvas.addEventListener('mousedown', handlePointerDown);
    globalThis.addEventListener('mousemove', handlePointerMove);
    globalThis.addEventListener('mouseup', handlePointerUp);
    canvas.addEventListener('wheel', handleWheel, { passive: false });

    app.on('update', () => {
      applyOrbitCamera();
    });

    if (modelUrl) {
      onStatusChange(`Carregando ${modelName}...`);
      app.assets.loadFromUrl(modelUrl, 'container', (error, asset) => {
        if (error || !asset?.resource) {
          onStatusChange('Falha ao carregar o modelo. Verifique se o GLB esta valido.');
          return;
        }

        modelEntity = asset.resource.instantiateRenderEntity();
        app.root.addChild(modelEntity);

        const aabb = computeCombinedAabb(modelEntity);
        if (aabb) {
          orbit.target.copy(aabb.center);
          const radius = Math.max(aabb.halfExtents.x, aabb.halfExtents.y, aabb.halfExtents.z);
          orbit.distance = Math.max(radius * 3.2, 2.5);
        }

        onStatusChange(`Modelo carregado: ${modelName}`);
      });
    } else {
      onStatusChange('Aguardando upload de arquivo .glb');
      applyOrbitCamera();
    }

    return () => {
      canvas.removeEventListener('mousedown', handlePointerDown);
      globalThis.removeEventListener('mousemove', handlePointerMove);
      globalThis.removeEventListener('mouseup', handlePointerUp);
      canvas.removeEventListener('wheel', handleWheel);
      globalThis.removeEventListener('resize', resizeCanvas);

      if (modelEntity) {
        modelEntity.destroy();
      }

      app.destroy();
    };
  }, [modelName, modelUrl, onStatusChange]);

  return (
    <section className="panel viewer-panel" aria-labelledby="viewer-heading">
      <div className="viewer-header">
        <h2 id="viewer-heading">Visualizador 3D</h2>
        <p className="panel-copy">Arraste com o mouse para orbitar e use a roda para zoom.</p>
      </div>
      <div className="viewer-shell">
        <canvas ref={canvasRef} className="viewer-canvas" aria-label="Visualizacao do modelo 3D" />
      </div>
    </section>
  );
}
