// Generated by GitHub Copilot
import PropTypes from 'prop-types';
import { useEffect, useMemo, useRef, useState } from 'react';
import { createPortal } from 'react-dom';

const MAX_FILE_SIZE_BYTES = 100 * 1024 * 1024;

/**
 * Displays upload controls with client-side validation for GLB files.
 * Security note: validates extension and size before handing file to app state.
 * @param {{
 *   onModelSelected: (file: File | null, errorMessage?: string) => void,
 *   selectedFileName: string
 * }} props
 * @returns {JSX.Element}
 */
export default function UploadPanel({ onModelSelected, selectedFileName }) {
  const [isOpen, setIsOpen] = useState(false);
  const fileInputRef = useRef(null);
  const sizeHint = useMemo(() => `${Math.floor(MAX_FILE_SIZE_BYTES / (1024 * 1024))}MB`, []);

  useEffect(() => {
    if (!isOpen) {
      return undefined;
    }

    globalThis.setTimeout(() => {
      fileInputRef.current?.focus();
    }, 0);

    /**
     * Fecha o modal quando a tecla Escape e pressionada.
     * @param {KeyboardEvent} event
     * @returns {void}
     */
    function handleEscape(event) {
      if (event.key === 'Escape') {
        setIsOpen(false);
      }
    }

    globalThis.addEventListener('keydown', handleEscape);
    return () => {
      globalThis.removeEventListener('keydown', handleEscape);
    };
  }, [isOpen]);

  /**
   * Handles file selection and validates basic input constraints.
   * @param {React.ChangeEvent<HTMLInputElement>} event
   * @returns {void}
   */
  function handleFileChange(event) {
    const file = event.target.files?.[0] ?? null;

    if (!file) {
      onModelSelected(null, 'Nenhum arquivo selecionado.');
      return;
    }

    if (!file.name.toLowerCase().endsWith('.glb')) {
      onModelSelected(null, 'Formato invalido. Use um arquivo .glb');
      return;
    }

    if (file.size > MAX_FILE_SIZE_BYTES) {
      onModelSelected(null, `Arquivo muito grande. Limite de ${sizeHint}.`);
      return;
    }

    onModelSelected(file);
    setIsOpen(false);
    event.target.value = '';
  }

  /**
   * Abre o modal e move foco para o campo de upload.
   * @returns {void}
   */
  function handleOpenModal() {
    setIsOpen(true);
  }

  /**
   * Fecha o modal de upload.
   * @returns {void}
   */
  function handleCloseModal() {
    setIsOpen(false);
  }

  return (
    <section className="upload-actions" aria-label="Controles de upload">
      <button type="button" className="upload-trigger" onClick={handleOpenModal}>
        Upload do Projeto
      </button>
      <p className="selected-file" aria-live="polite">
        {selectedFileName ? `Modelo ativo: ${selectedFileName}` : 'Nenhum modelo carregado'}
      </p>

      {isOpen
        ? createPortal(
            <div className="upload-modal-layer">
              <button
                type="button"
                className="upload-modal-backdrop"
                onClick={handleCloseModal}
                aria-label="Fechar modal"
              />
              <dialog className="upload-modal" open aria-labelledby="upload-modal-heading">
                <div className="upload-modal-header">
                  <h2 id="upload-modal-heading">Enviar arquivo GLB</h2>
                  <button type="button" className="modal-close" onClick={handleCloseModal} aria-label="Fechar modal">
                    Fechar
                  </button>
                </div>

                <p className="panel-copy">Escolha um arquivo .glb de ate {sizeHint} para carregar no visualizador.</p>

                <label className="upload-field" htmlFor="modelUpload">
                  <span>Arquivo .glb</span>
                  <input
                    ref={fileInputRef}
                    id="modelUpload"
                    name="modelUpload"
                    type="file"
                    accept=".glb,model/gltf-binary"
                    onChange={handleFileChange}
                  />
                </label>
              </dialog>
            </div>,
            document.body
          )
        : null}
    </section>
  );
}

UploadPanel.propTypes = {
  onModelSelected: PropTypes.func.isRequired,
  selectedFileName: PropTypes.string.isRequired
};
