// Generated by GitHub Copilot
import { useCallback, useEffect, useState } from 'react';
import './App.css';
import ModelViewer from './components/ModelViewer';
import UploadPanel from './components/UploadPanel';

/**
 * Main screen for uploading and previewing architecture models exported as GLB.
 * @returns {JSX.Element}
 */
function App() {
  const [modelUrl, setModelUrl] = useState('');
  const [modelName, setModelName] = useState('');
  const [statusMessage, setStatusMessage] = useState('Aguardando upload de arquivo .glb');
  const [errorMessage, setErrorMessage] = useState('');

  /**
   * Stores or clears the current model while releasing old object URLs.
   * @param {File | null} file
   * @param {string} [validationError]
   * @returns {void}
   */
  const handleModelSelected = useCallback((file, validationError) => {
    setErrorMessage('');

    setModelUrl((currentUrl) => {
      if (currentUrl) {
        URL.revokeObjectURL(currentUrl);
      }

      if (!file) {
        setModelName('');
        if (validationError) {
          setErrorMessage(validationError);
          setStatusMessage('Envie um modelo .glb valido para continuar.');
        }
        return '';
      }

      setModelName(file.name);
      setStatusMessage(`Arquivo pronto: ${file.name}`);
      return URL.createObjectURL(file);
    });
  }, []);

  useEffect(() => {
    return () => {
      if (modelUrl) {
        URL.revokeObjectURL(modelUrl);
      }
    };
  }, [modelUrl]);

  return (
    <main className="layout">
      <section className="topbar" aria-label="Acoes do projeto">
        <div className="topbar-copy">
          <h1>Viewer de Projetos SketchUp</h1>
          <p>Foco total no 3D: envie um .glb e visualize em tela ampla.</p>
        </div>
        <UploadPanel onModelSelected={handleModelSelected} selectedFileName={modelName} />
      </section>

      <section className="workspace" aria-label="Area principal">
        <ModelViewer modelUrl={modelUrl} modelName={modelName} onStatusChange={setStatusMessage} />
      </section>

      <footer className="status-bar" aria-live="polite">
        <p>{statusMessage}</p>
        {errorMessage ? <p className="status-error">{errorMessage}</p> : null}
      </footer>
    </main>
  );
}

export default App;
